### ISSUE TITLE
Example breaks on binder

### ISSUE THREAD

**Issue by stwunsch** [cms-opendata-analyses/DimuonSpectrumNanoAODOutreachAnalysis#3]
Such as @katilp found out: The example breaks on binder because of some weirdness between how ROOT detects the resources for multi-threading and how docker tells us the available resources. However, I would just disable the multi-threading for the examples here and we are safe.

@katilp Is this fine for you?
@katilp Second question: How do we proceed with the update to the record on the portal? I can just fix it for binder by pushing to the repo, shall I also make an issue to the cernopendata repo?

Thanks :)

**Comment by katilp** [comment]
That should be fine.

For the portal record, what we discussed with @tiborsimko : you canjust make another release and we can attach the zip with brief release comments. Both old and new can stay visible and no need to change the DOI.

**Comment by stwunsch** [comment]
I'll make a PR to the open data portal.

**Comment by stwunsch** [comment]
The PR is [here](https://github.com/cernopendata/opendata.cern.ch/issues/2828).
